name: Send TG bot message

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      status:
        required: true
        type: string

jobs:
  sendmessage:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/Saturnych/tgbot-sendmessage
      - name: Send bot message to group
        id: sendmessage
        uses: Saturnych/tgbot-sendmessage@develop
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat: ${{ secrets.TELEGRAM_BOT_GROUP }}
          text: "${{ inputs.name }} - the result status: ${{ inputs.status }}"

      - name: Get output time
        run: echo 'The event happened at ${{ steps.sendmessage.outputs.time }}'
